name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install
        run: |
          sudo apt update
          sudo apt -y install clang-9 libclang-9-dev cmake libgc-dev libgmp-dev binutils-dev zlib1g-dev libncurses-dev libboost-filesystem-dev libboost-regex-dev libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-iostreams-dev libunwind-dev liblzma-dev libelf1 libelf-dev libbsd-dev sbcl
      - name: build
        run: |
          git clone https://github.com/clasp-developers/clasp
          cd clasp && ./waf configure build_dboehm
      - name: test
        run: |
          clasp/build/boehm/iclasp-boehm -e '(core:quit)'
